// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package sockstream

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SockstreamCall struct {
	_          structs.HostLayout
	Cookie     uint64
	Base       uint64
	NrSegs     uint64
	Offset     uint64
	Direction  uint32
	Ubuf       uint32
	RemoteIp   [16]uint8
	RemotePort uint16
	HasRemote  uint8
	Protocol   uint8
	Reserved   uint32
}

type SockstreamChunk struct {
	_    structs.HostLayout
	H    SockstreamChunkHeader
	Data [4096]uint8
	Cur  struct {
		_       structs.HostLayout
		Sent    uint64
		Offset  uint64
		Segment uint64
	}
}

type SockstreamChunkHeader struct {
	_          structs.HostLayout
	Cookie     uint64
	StartNs    uint64
	Netns      uint64
	Pid        uint32
	Offset     uint32
	Len        uint16
	LocalPort  uint16
	RemotePort uint16
	Direction  uint8
	Family     uint8
	LocalIp    [16]uint8
	RemoteIp   [16]uint8
	Comm       [16]int8
	Protocol   uint8
	_          [7]byte
}

type SockstreamConfig struct {
	_     structs.HostLayout
	Netns uint64
	Port  uint16
	_     [6]byte
}

type SockstreamStreamKey struct {
	_         structs.HostLayout
	Cookie    uint64
	Direction uint32
	Reserved  uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	SockstreamMapCalls               = "calls"
	SockstreamMapCaptured            = "captured"
	SockstreamMapChunks              = "chunks"
	SockstreamMapLost                = "lost"
	SockstreamMapScratch             = "scratch"
	SockstreamMapSettings            = "settings"
	SockstreamProgDatagram6SendEnter = "datagram6_send_enter"
	SockstreamProgDatagram6SendExit  = "datagram6_send_exit"
	SockstreamProgDatagramSendEnter  = "datagram_send_enter"
	SockstreamProgDatagramSendExit   = "datagram_send_exit"
	SockstreamProgSocketFreed        = "socket_freed"
	SockstreamProgStreamRecvEnter    = "stream_recv_enter"
	SockstreamProgStreamRecvEnterOld = "stream_recv_enter_old"
	SockstreamProgStreamRecvExit     = "stream_recv_exit"
	SockstreamProgStreamRecvExitOld  = "stream_recv_exit_old"
	SockstreamProgStreamSendEnter    = "stream_send_enter"
	SockstreamProgStreamSendExit     = "stream_send_exit"
	SockstreamVarHasSocketCookie     = "has_socket_cookie"
)

// LoadSockstream returns the embedded CollectionSpec for Sockstream.
func LoadSockstream() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockstreamBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Sockstream: %w", err)
	}

	return spec, err
}

// LoadSockstreamObjects loads Sockstream and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SockstreamObjects
//	*SockstreamPrograms
//	*SockstreamMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSockstreamObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSockstream()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SockstreamSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockstreamSpecs struct {
	SockstreamProgramSpecs
	SockstreamMapSpecs
	SockstreamVariableSpecs
}

// SockstreamProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockstreamProgramSpecs struct {
	Datagram6SendEnter *ebpf.ProgramSpec `ebpf:"datagram6_send_enter"`
	Datagram6SendExit  *ebpf.ProgramSpec `ebpf:"datagram6_send_exit"`
	DatagramSendEnter  *ebpf.ProgramSpec `ebpf:"datagram_send_enter"`
	DatagramSendExit   *ebpf.ProgramSpec `ebpf:"datagram_send_exit"`
	SocketFreed        *ebpf.ProgramSpec `ebpf:"socket_freed"`
	StreamRecvEnter    *ebpf.ProgramSpec `ebpf:"stream_recv_enter"`
	StreamRecvEnterOld *ebpf.ProgramSpec `ebpf:"stream_recv_enter_old"`
	StreamRecvExit     *ebpf.ProgramSpec `ebpf:"stream_recv_exit"`
	StreamRecvExitOld  *ebpf.ProgramSpec `ebpf:"stream_recv_exit_old"`
	StreamSendEnter    *ebpf.ProgramSpec `ebpf:"stream_send_enter"`
	StreamSendExit     *ebpf.ProgramSpec `ebpf:"stream_send_exit"`
}

// SockstreamMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockstreamMapSpecs struct {
	Calls    *ebpf.MapSpec `ebpf:"calls"`
	Captured *ebpf.MapSpec `ebpf:"captured"`
	Chunks   *ebpf.MapSpec `ebpf:"chunks"`
	Lost     *ebpf.MapSpec `ebpf:"lost"`
	Scratch  *ebpf.MapSpec `ebpf:"scratch"`
	Settings *ebpf.MapSpec `ebpf:"settings"`
}

// SockstreamVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockstreamVariableSpecs struct {
	HasSocketCookie *ebpf.VariableSpec `ebpf:"has_socket_cookie"`
}

// SockstreamObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSockstreamObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockstreamObjects struct {
	SockstreamPrograms
	SockstreamMaps
	SockstreamVariables
}

func (o *SockstreamObjects) Close() error {
	return _SockstreamClose(
		&o.SockstreamPrograms,
		&o.SockstreamMaps,
	)
}

// SockstreamMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSockstreamObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockstreamMaps struct {
	Calls    *ebpf.Map `ebpf:"calls"`
	Captured *ebpf.Map `ebpf:"captured"`
	Chunks   *ebpf.Map `ebpf:"chunks"`
	Lost     *ebpf.Map `ebpf:"lost"`
	Scratch  *ebpf.Map `ebpf:"scratch"`
	Settings *ebpf.Map `ebpf:"settings"`
}

func (m *SockstreamMaps) Close() error {
	return _SockstreamClose(
		m.Calls,
		m.Captured,
		m.Chunks,
		m.Lost,
		m.Scratch,
		m.Settings,
	)
}

// SockstreamVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSockstreamObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockstreamVariables struct {
	HasSocketCookie *ebpf.Variable `ebpf:"has_socket_cookie"`
}

// SockstreamPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSockstreamObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockstreamPrograms struct {
	Datagram6SendEnter *ebpf.Program `ebpf:"datagram6_send_enter"`
	Datagram6SendExit  *ebpf.Program `ebpf:"datagram6_send_exit"`
	DatagramSendEnter  *ebpf.Program `ebpf:"datagram_send_enter"`
	DatagramSendExit   *ebpf.Program `ebpf:"datagram_send_exit"`
	SocketFreed        *ebpf.Program `ebpf:"socket_freed"`
	StreamRecvEnter    *ebpf.Program `ebpf:"stream_recv_enter"`
	StreamRecvEnterOld *ebpf.Program `ebpf:"stream_recv_enter_old"`
	StreamRecvExit     *ebpf.Program `ebpf:"stream_recv_exit"`
	StreamRecvExitOld  *ebpf.Program `ebpf:"stream_recv_exit_old"`
	StreamSendEnter    *ebpf.Program `ebpf:"stream_send_enter"`
	StreamSendExit     *ebpf.Program `ebpf:"stream_send_exit"`
}

func (p *SockstreamPrograms) Close() error {
	return _SockstreamClose(
		p.Datagram6SendEnter,
		p.Datagram6SendExit,
		p.DatagramSendEnter,
		p.DatagramSendExit,
		p.SocketFreed,
		p.StreamRecvEnter,
		p.StreamRecvEnterOld,
		p.StreamRecvExit,
		p.StreamRecvExitOld,
		p.StreamSendEnter,
		p.StreamSendExit,
	)
}

func _SockstreamClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockstream_bpfel.o
var _SockstreamBytes []byte
