// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package tlsprobe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TlsActiveConnect struct {
	_        structs.HostLayout
	Key      TlsSslKey
	Emitted  uint8
	Reserved [7]uint8
}

type TlsBioKey struct {
	_        structs.HostLayout
	Bio      uint64
	Pid      uint32
	Reserved uint32
}

type TlsCall struct {
	_        structs.HostLayout
	Ssl      uint64
	Arg      uint64
	Fd       int32
	Reserved uint32
}

type TlsEvent struct {
	_          structs.HostLayout
	StartNs    uint64
	Netns      uint64
	Pid        uint32
	LocalPort  uint16
	RemotePort uint16
	Family     uint8
	Source     uint8
	LocalIp    [16]uint8
	RemoteIp   [16]uint8
	Hostname   [256]int8
	Comm       [16]int8
	_          [6]byte
}

type TlsSslKey struct {
	_        structs.HostLayout
	Ssl      uint64
	Pid      uint32
	Reserved uint32
}

type TlsSslState struct {
	_        structs.HostLayout
	Fd       int32
	Source   uint8
	Hostname [256]int8
	Reserved [3]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TlsMapActiveConnects       = "active_connects"
	TlsMapBioCalls             = "bio_calls"
	TlsMapBioFds               = "bio_fds"
	TlsMapCalls                = "calls"
	TlsMapEvents               = "events"
	TlsMapSslStates            = "ssl_states"
	TlsMapTargetNetns          = "target_netns"
	TlsProgBioFreeEnter        = "bio_free_enter"
	TlsProgBioNewSocketEnter   = "bio_new_socket_enter"
	TlsProgBioNewSocketReturn  = "bio_new_socket_return"
	TlsProgConnectEnter        = "connect_enter"
	TlsProgConnectReturn       = "connect_return"
	TlsProgConnectTcpSend      = "connect_tcp_send"
	TlsProgCtrlEnter           = "ctrl_enter"
	TlsProgCtrlReturn          = "ctrl_return"
	TlsProgFreeEnter           = "free_enter"
	TlsProgGetServernameEnter  = "get_servername_enter"
	TlsProgGetServernameReturn = "get_servername_return"
	TlsProgHandshakeEnter      = "handshake_enter"
	TlsProgSet0RbioEnter       = "set0_rbio_enter"
	TlsProgSetBioEnter         = "set_bio_enter"
	TlsProgSetFdEnter          = "set_fd_enter"
	TlsProgSetFdReturn         = "set_fd_return"
)

// LoadTls returns the embedded CollectionSpec for Tls.
func LoadTls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tls: %w", err)
	}

	return spec, err
}

// LoadTlsObjects loads Tls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TlsObjects
//	*TlsPrograms
//	*TlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTlsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsSpecs struct {
	TlsProgramSpecs
	TlsMapSpecs
	TlsVariableSpecs
}

// TlsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsProgramSpecs struct {
	BioFreeEnter        *ebpf.ProgramSpec `ebpf:"bio_free_enter"`
	BioNewSocketEnter   *ebpf.ProgramSpec `ebpf:"bio_new_socket_enter"`
	BioNewSocketReturn  *ebpf.ProgramSpec `ebpf:"bio_new_socket_return"`
	ConnectEnter        *ebpf.ProgramSpec `ebpf:"connect_enter"`
	ConnectReturn       *ebpf.ProgramSpec `ebpf:"connect_return"`
	ConnectTcpSend      *ebpf.ProgramSpec `ebpf:"connect_tcp_send"`
	CtrlEnter           *ebpf.ProgramSpec `ebpf:"ctrl_enter"`
	CtrlReturn          *ebpf.ProgramSpec `ebpf:"ctrl_return"`
	FreeEnter           *ebpf.ProgramSpec `ebpf:"free_enter"`
	GetServernameEnter  *ebpf.ProgramSpec `ebpf:"get_servername_enter"`
	GetServernameReturn *ebpf.ProgramSpec `ebpf:"get_servername_return"`
	HandshakeEnter      *ebpf.ProgramSpec `ebpf:"handshake_enter"`
	Set0RbioEnter       *ebpf.ProgramSpec `ebpf:"set0_rbio_enter"`
	SetBioEnter         *ebpf.ProgramSpec `ebpf:"set_bio_enter"`
	SetFdEnter          *ebpf.ProgramSpec `ebpf:"set_fd_enter"`
	SetFdReturn         *ebpf.ProgramSpec `ebpf:"set_fd_return"`
}

// TlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsMapSpecs struct {
	ActiveConnects *ebpf.MapSpec `ebpf:"active_connects"`
	BioCalls       *ebpf.MapSpec `ebpf:"bio_calls"`
	BioFds         *ebpf.MapSpec `ebpf:"bio_fds"`
	Calls          *ebpf.MapSpec `ebpf:"calls"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	SslStates      *ebpf.MapSpec `ebpf:"ssl_states"`
	TargetNetns    *ebpf.MapSpec `ebpf:"target_netns"`
}

// TlsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsVariableSpecs struct {
}

// TlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsObjects struct {
	TlsPrograms
	TlsMaps
	TlsVariables
}

func (o *TlsObjects) Close() error {
	return _TlsClose(
		&o.TlsPrograms,
		&o.TlsMaps,
	)
}

// TlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsMaps struct {
	ActiveConnects *ebpf.Map `ebpf:"active_connects"`
	BioCalls       *ebpf.Map `ebpf:"bio_calls"`
	BioFds         *ebpf.Map `ebpf:"bio_fds"`
	Calls          *ebpf.Map `ebpf:"calls"`
	Events         *ebpf.Map `ebpf:"events"`
	SslStates      *ebpf.Map `ebpf:"ssl_states"`
	TargetNetns    *ebpf.Map `ebpf:"target_netns"`
}

func (m *TlsMaps) Close() error {
	return _TlsClose(
		m.ActiveConnects,
		m.BioCalls,
		m.BioFds,
		m.Calls,
		m.Events,
		m.SslStates,
		m.TargetNetns,
	)
}

// TlsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsVariables struct {
}

// TlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsPrograms struct {
	BioFreeEnter        *ebpf.Program `ebpf:"bio_free_enter"`
	BioNewSocketEnter   *ebpf.Program `ebpf:"bio_new_socket_enter"`
	BioNewSocketReturn  *ebpf.Program `ebpf:"bio_new_socket_return"`
	ConnectEnter        *ebpf.Program `ebpf:"connect_enter"`
	ConnectReturn       *ebpf.Program `ebpf:"connect_return"`
	ConnectTcpSend      *ebpf.Program `ebpf:"connect_tcp_send"`
	CtrlEnter           *ebpf.Program `ebpf:"ctrl_enter"`
	CtrlReturn          *ebpf.Program `ebpf:"ctrl_return"`
	FreeEnter           *ebpf.Program `ebpf:"free_enter"`
	GetServernameEnter  *ebpf.Program `ebpf:"get_servername_enter"`
	GetServernameReturn *ebpf.Program `ebpf:"get_servername_return"`
	HandshakeEnter      *ebpf.Program `ebpf:"handshake_enter"`
	Set0RbioEnter       *ebpf.Program `ebpf:"set0_rbio_enter"`
	SetBioEnter         *ebpf.Program `ebpf:"set_bio_enter"`
	SetFdEnter          *ebpf.Program `ebpf:"set_fd_enter"`
	SetFdReturn         *ebpf.Program `ebpf:"set_fd_return"`
}

func (p *TlsPrograms) Close() error {
	return _TlsClose(
		p.BioFreeEnter,
		p.BioNewSocketEnter,
		p.BioNewSocketReturn,
		p.ConnectEnter,
		p.ConnectReturn,
		p.ConnectTcpSend,
		p.CtrlEnter,
		p.CtrlReturn,
		p.FreeEnter,
		p.GetServernameEnter,
		p.GetServernameReturn,
		p.HandshakeEnter,
		p.Set0RbioEnter,
		p.SetBioEnter,
		p.SetFdEnter,
		p.SetFdReturn,
	)
}

func _TlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tls_x86_bpfel.o
var _TlsBytes []byte
