// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package dropprobe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type DropDropKey struct {
	_          structs.HostLayout
	Netns      uint64
	Location   uint64
	Source     [16]uint8
	Target     [16]uint8
	Reason     uint32
	SourcePort uint16
	TargetPort uint16
	Family     uint8
	Protocol   uint8
	_          [6]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	DropMapDrops      = "drops"
	DropMapNamespaces = "namespaces"
	DropProgCountDrop = "count_drop"
)

// LoadDrop returns the embedded CollectionSpec for Drop.
func LoadDrop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DropBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Drop: %w", err)
	}

	return spec, err
}

// LoadDropObjects loads Drop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DropObjects
//	*DropPrograms
//	*DropMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDropObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDrop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DropSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DropSpecs struct {
	DropProgramSpecs
	DropMapSpecs
	DropVariableSpecs
}

// DropProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DropProgramSpecs struct {
	CountDrop *ebpf.ProgramSpec `ebpf:"count_drop"`
}

// DropMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DropMapSpecs struct {
	Drops      *ebpf.MapSpec `ebpf:"drops"`
	Namespaces *ebpf.MapSpec `ebpf:"namespaces"`
}

// DropVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DropVariableSpecs struct {
}

// DropObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type DropObjects struct {
	DropPrograms
	DropMaps
	DropVariables
}

func (o *DropObjects) Close() error {
	return _DropClose(
		&o.DropPrograms,
		&o.DropMaps,
	)
}

// DropMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type DropMaps struct {
	Drops      *ebpf.Map `ebpf:"drops"`
	Namespaces *ebpf.Map `ebpf:"namespaces"`
}

func (m *DropMaps) Close() error {
	return _DropClose(
		m.Drops,
		m.Namespaces,
	)
}

// DropVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type DropVariables struct {
}

// DropPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type DropPrograms struct {
	CountDrop *ebpf.Program `ebpf:"count_drop"`
}

func (p *DropPrograms) Close() error {
	return _DropClose(
		p.CountDrop,
	)
}

func _DropClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed drop_bpfel.o
var _DropBytes []byte
